package formularios;


import java.io.FileInputStream;
import java.io.ObjectInputStream;
import java.io.Serializable;
import java.util.StringTokenizer;
import javax.swing.JOptionPane;
import modelo.FechaException;
import modelo.ReportePago;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


public class Caja extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form Caja
     */
    public Caja() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabelImagen1 = new javax.swing.JLabel();
        jLabelImagen2 = new javax.swing.JLabel();
        jLabelImagen3 = new javax.swing.JLabel();
        jLabelCoche = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(76, 145, 181));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setFont(new java.awt.Font("Comic Sans MS", 1, 25)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("BIENVENIDOS A CAJA       ");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 390, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton1.setText("DIA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, 160, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButton2.setText("MES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 160, 30));

        jLabelImagen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-dinero-48.png"))); // NOI18N
        jPanel1.add(jLabelImagen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, -1, 40));

        jLabelImagen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-montón-de-dinero-48.png"))); // NOI18N
        jPanel1.add(jLabelImagen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 250, -1, 40));

        jLabelImagen3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-bolsa-de-dinero-50.png"))); // NOI18N
        jPanel1.add(jLabelImagen3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, -1, -1));

        jLabelCoche.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-coche-100.png"))); // NOI18N
        jPanel1.add(jLabelCoche, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Lovepik_com-450038768-isometric parking in vector.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 420, 290));

        jButton3.setBackground(new java.awt.Color(255, 255, 51));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icons8-doble-izquierda-26.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, 690, 330));

        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo.png"))); // NOI18N
        getContentPane().add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         ReporteMes rm = new ReporteMes ();
        ReportePago boletas[] = new ReportePago[0];
        String fecha = null;
        int mes = 0,anio = 0;
            boolean bandera = true;
            String palabra[]=new String[2];
            int j;             
            j=0;     
            fecha = JOptionPane.showInputDialog("Introduzca FECHA (mes/anio) ");
            try{    
                
                
                        //StringTokenizer nos ayudar a separar una cadena en varias partes segun la condicion en en su segundo argumento
                StringTokenizer parti=new StringTokenizer(fecha,"/");

                    //Sirve para verificar si existe elementos en la cadena segun la condicion establecida en el segundo argumento
                while(parti.hasMoreElements()){ 
                    if(j>=2){
                        throw new FechaException();
                    } 
                     palabra[j]=parti.nextToken();
                    j++;  
                }

                        //Integer.parseInt sirve para convertir una cadena a un numero del tipo "entero"
                mes=Integer.parseInt(palabra[0]);
                anio=Integer.parseInt(palabra[1]);

                        //llamamos al mento calculo de la clase "CalculaFecha"
                calculoMes(mes,anio);

                bandera=true;    
                }
                    //Si no se cumple ninguna excepcion anterior pero hay un error detectado este catch nos ayudara a visualizar el error
                catch(FechaException e){
                    JOptionPane.showMessageDialog(null, "La Fecha Ingresada NO EXISTE");  
                    bandera=false;
                } 
                catch(NullPointerException a){
                    
                    bandera=false;
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "Error de formato de la fecha");  
                    bandera=false;
                 }
    
        String matriz [][] = new String [cantBoletasM(mes,anio)][5];
        
            
        try
        {
            FileInputStream fis=new FileInputStream("Boletas1.txt");
            ObjectInputStream H=new ObjectInputStream(fis);
            boletas=(ReportePago[])H.readObject();
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo o crearlo");

        }
        int f=0;
        if(bandera==true){
            for(int i=0;i<boletas.length;i++){
                if((boletas[i].getAnio_Salida()==anio && boletas[i].getMes_Salida() == mes) ){
                    String fechaT =boletas[i].getDia_Salida()+" / "+boletas[i].getMes_Salida()+" / "+boletas[i].getAnio_Salida();
                    String cod="000"+boletas[i].getCodigoBoleta();
                    matriz [f][0]=cod;
                    matriz [f][1]=boletas[i].getTicket().apellido() +" "+boletas[i].getTicket().nombre() ;
                    matriz [f][2]=boletas[i].getTicket().placa();
                    matriz [f][3]=fechaT;
                    matriz [f][4]=boletas[i].pago();      
                    f++;
             
                }
                 
        }

        rm.setMontoMes(acumuladoMes(mes,anio));
        rm.mostrar(matriz);
        
        rm.setVisible(true);
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ReporteCajaDia cDia = new ReporteCajaDia ();
        ReportePago boletas[] = new ReportePago[0];
        String fecha = null;
        int dia = 0,mes = 0,anio = 0;
            boolean bandera = true;
            String palabra[]=new String[3];
            int j;             
            j=0;        
            fecha = JOptionPane.showInputDialog("Introduzca FECHA (dia/mes/anio) ");
            try{    
                
                
                        //StringTokenizer nos ayudar a separar una cadena en varias partes segun la condicion en en su segundo argumento
                StringTokenizer parti=new StringTokenizer(fecha,"/");

                    //Sirve para verificar si existe elementos en la cadena segun la condicion establecida en el segundo argumento
                while(parti.hasMoreElements()){ 
                    if(j>=3){
                        throw new FechaException();
                    } 
                     palabra[j]=parti.nextToken();
                    j++;  
                }

                        //Integer.parseInt sirve para convertir una cadena a un numero del tipo "entero"
                dia=Integer.parseInt(palabra[0]);
                mes=Integer.parseInt(palabra[1]);
                anio=Integer.parseInt(palabra[2]);

                        //llamamos al mento calculo de la clase "CalculaFecha"
                calculo(dia,mes,anio);

                bandera=true;    
                }
                    //Si no se cumple ninguna excepcion anterior pero hay un error detectado este catch nos ayudara a visualizar el error
                catch(FechaException e){
                    JOptionPane.showMessageDialog(null, "La Fecha Ingresada NO EXISTE");  
                    bandera=false;
                }  
                catch(NullPointerException a){
                    
                    bandera=false;
                }
                catch(NumberFormatException e){
                    JOptionPane.showMessageDialog(null, "La Fecha Ingresada NO EXISTE");  
                    bandera=false;
                 }    
        String matriz [][] = new String [cantBoletas(dia,mes,anio)][5];
            
        try
        {
            FileInputStream fis=new FileInputStream("Boletas1.txt");
            ObjectInputStream H=new ObjectInputStream(fis);
            boletas=(ReportePago[])H.readObject();
            
            
        }
        catch(NullPointerException a){
            JOptionPane.showMessageDialog(null,"Cancelar Archivo");
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo o crearlo");

        }

        int f=0;
        if(bandera==true){
            for(int i=0;i<boletas.length;i++){
                if((boletas[i].getAnio_Salida()==anio && boletas[i].getMes_Salida() == mes) && boletas[i].getDia_Salida() == dia){
                    String fechaT =boletas[i].getDia_Salida()+" / "+boletas[i].getMes_Salida()+" / "+boletas[i].getAnio_Salida();
                    String cod="000"+boletas[i].getCodigoBoleta();
                    matriz [f][0]=cod;
                    matriz [f][1]=boletas[i].getTicket().apellido() +" "+boletas[i].getTicket().nombre() ;
                    matriz [f][2]=boletas[i].getTicket().placa();
                    matriz [f][3]=fechaT;
                    matriz [f][4]=boletas[i].pago();     
                    f++;
                }
                 
        }

        cDia.setMontoDia(acumuladoDia(dia,mes,anio));
        cDia.setDiaReporte(dia,mes,anio);
        cDia.mostrar(matriz);
        
        cDia.setVisible(true);
    }        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.setVisible(false);
       SistemaAdmin sis = new SistemaAdmin ();
       sis.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed


    public void calculo(int dia,int mes,int anio) throws FechaException{
        
       if(dia>0 && anio>0){ 
            switch(mes){

                case 1:if(dia>31){
                    throw new FechaException();
                    }break;

                case 2:
                    if(anio%4==0 && ( anio%100!=0 || anio%400==0)){
                       if(dia>29){
                            throw new FechaException();
                        }   
                    }else{
                        if(dia>28){
                            throw new FechaException();
                        }
                    }
                    break;

                case 3:
                    if(dia>31){
                        throw new FechaException();
                    }break;

                case 4:if(dia>30){
                    throw new FechaException();
                    } break;

                case 5:if(dia>31){
                    throw new FechaException();
                    }break;

                case 6:if(dia>30){
                    throw new FechaException();
                     } break;

                case 7:if(dia>31){
                    throw new FechaException();
                    }break;

                case 8:if(dia>31){
                    throw new FechaException();
                    }break;

                case 9:if(dia>30){
                    throw new FechaException();
                    } break;

                case 10:if(dia>31){
                    throw new FechaException();
                    }break;

                case 11:if(dia>30){
                    throw new FechaException();
                    } break;

                case 12:if(dia>31){
                    throw new FechaException();
                    }break;  

                default : throw new FechaException();
            }
        }
    else{
        throw new FechaException();
    }
    }
    
    public double acumuladoDia(int dia,int mes,int anio){
        double montoTotal=0;
         ReportePago boletas[] = new ReportePago[0];   
        try
        {
            FileInputStream fis=new FileInputStream("Boletas1.txt");
            ObjectInputStream H=new ObjectInputStream(fis);
            boletas=(ReportePago[])H.readObject();
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo o crearlo");

        }
        for(int i=0;i<boletas.length;i++){
            if(dia==boletas[i].getDia_Salida() && mes==boletas[i].getMes_Salida() && anio==boletas[i].getAnio_Salida() && boletas[i].getCodigoBoleta()!=0){
                montoTotal=montoTotal+boletas[i].getPago_total();
            }        
        }
        montoTotal=Math.round(montoTotal*10.0)/10.0;
        return montoTotal;
    }
    
       public int cantBoletas(int dia, int mes, int anio){
        
        ReportePago boletas[] = new ReportePago[0];
        try
        {
            FileInputStream fis=new FileInputStream("Boletas1.txt");
            ObjectInputStream H=new ObjectInputStream(fis);
            boletas=(ReportePago[])H.readObject();
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo o crearlo");

        }
        

        int cant=0;
        for(int i=0;i<boletas.length;i++){
            if((boletas[i].getAnio_Salida()==anio && boletas[i].getMes_Salida() == mes) && boletas[i].getDia_Salida() == dia){
                cant++;
            }
        }
        return cant;
    }
    
        public int cantBoletasM(int mes, int anio){
        int cant=0;
        ReportePago boletas[] = new ReportePago[0];    
        try
        {
            FileInputStream fis=new FileInputStream("Boletas1.txt");
            ObjectInputStream H=new ObjectInputStream(fis);
            boletas=(ReportePago[])H.readObject();
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo o crearlo");

        }
        for(int i=0;i<boletas.length;i++){
            if((boletas[i].getAnio_Salida()==anio && boletas[i].getMes_Salida() == mes)){
                cant++;
            }
        }
        return cant;
    }   
    
     public double acumuladoMes(int mes,int anio){
        double montoTotal=0;
        ReportePago boletas[] = new ReportePago [0];    
        try
        {
            FileInputStream fis=new FileInputStream("Boletas1.txt");
            ObjectInputStream H=new ObjectInputStream(fis);
            boletas=(ReportePago[])H.readObject();
            
            
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,"Error al abrir archivo o crearlo");

        }
        for(int i=0;i<boletas.length;i++){
            if( mes==boletas[i].getMes_Salida() && anio==boletas[i].getAnio_Salida() && boletas[i].getCodigoBoleta()!=0){
                montoTotal=montoTotal+boletas[i].getPago_total();
            }        
        }
        montoTotal=Math.round(montoTotal*10.0)/10.0;
        return montoTotal;
    }        
        
    public void calculoMes(int mes,int anio)throws FechaException{
        if(anio>0){
            if(mes<=0 || mes>12){
                throw new FechaException();
            }
        }else{
            throw new FechaException();
        }
    }
         
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Caja.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Caja().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelCoche;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelImagen1;
    private javax.swing.JLabel jLabelImagen2;
    private javax.swing.JLabel jLabelImagen3;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
